version: "3"
services:
  mongo:
    image: mongo
    restart: always
    container_name: mongo
    volumes:
      - ./database:/data
    ports:
      - "27017:27017"

  mongo-init:
    build: docker/mongo-init
    links:
      - mongo


  discovery-server:
    build:
      context: discovery-server/
    container_name: discovery-server
    ports:
      - "8761:8761"

  catalog-service:
    build:
      context: catalog-service/
      dockerfile: Dockerfile
    container_name: catalog-service
    ports:
      - "8081:8081"
    environment:
      - EUREKA_SERVER=http://discovery-server:8761/eureka/
    links:
      - discovery-server
    depends_on:
      - discovery-server

  comments-service:
    build:
      context: comments-service/
      dockerfile: Docker/Dockerfile
    container_name: comments-service
    ports:
      - "8084:8084"
    environment:
      - EUREKA_SERVER=http://discovery-server:8761/eureka/
      - SPRING_DATA_MONGODB_HOST=mongo
    links:
      - mongo
      - discovery-server
    depends_on:
      - mongo
      - discovery-server

  ratings-service:
    build:
      context: ratings-service/
      dockerfile: Dockerfile
    container_name: ratings-service
    ports:
      - "8083:8083"
    environment:
      - EUREKA_SERVER=http://discovery-server:8761/eureka/
      - SPRING_DATA_MONGODB_HOST=mongo
    links:
      - mongo
      - discovery-server
    depends_on:
      - mongo
      - discovery-server

  info-service:
    build:
      context: info-service/
      dockerfile: Dockerfile
    container_name: info-service
    ports:
      - "8082:8082"
    environment:
      - EUREKA_SERVER=http://discovery-server:8761/eureka/
      - theMovieDBApiKey=
    links:
      - discovery-server
    depends_on:
      - discovery-server

  grafana-server:
    build: docker/grafana
    container_name: grafana-server
    ports:
      - 3000:3000

  prometheus-server:
    build: docker/prometheus
    container_name: prometheus-server
    ports:
      - 9090:9090