{
 "title": "Movie Microservices",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "HTTP Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count[1m]))",
     "legendFormat": "HTTP Requests"
    }
   ]
  },
  {
   "title": "Max HTTP Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(http_server_requests_seconds_max{status!~\"5..\"})",
     "legendFormat": "Max HTTP Requests"
    }
   ]
  },
  {
   "title": "Circuit breaker successful rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(resilience4j_circuitbreaker_calls_seconds_count{instance=\"catalog-service:8081\",job=\"catalog-service\",kind=\"successful\",name=\"comment\"} [1m])",
     "legendFormat": "Comment service"
    },
    {
     "expr": "rate(resilience4j_circuitbreaker_calls_seconds_count{instance=\"catalog-service:8081\",job=\"catalog-service\",kind=\"successful\",name=\"info\"} [1m])\t",
     "legendFormat": "Info service"
    },
    {
     "expr": "rate(resilience4j_circuitbreaker_calls_seconds_count{instance=\"catalog-service:8081\",job=\"catalog-service\",kind=\"successful\",name=\"rating\"} [1m])\t",
     "legendFormat": "Rating service"
    }
   ]
  },
  {
   "title": "Circuit breaker failure rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(resilience4j_circuitbreaker_calls_seconds_count{instance=\"catalog-service:8081\",job=\"catalog-service\",kind=\"failed\",name=\"comment\"} [1m])",
     "legendFormat": "Comment service"
    },
    {
     "expr": "rate(resilience4j_circuitbreaker_calls_seconds_count{instance=\"catalog-service:8081\",job=\"catalog-service\",kind=\"failed\",name=\"info\"} [1m])\t",
     "legendFormat": "Info service"
    },
    {
     "expr": "rate(resilience4j_circuitbreaker_calls_seconds_count{instance=\"catalog-service:8081\",job=\"catalog-service\",kind=\"failed\",name=\"rating\"} [1m])\t",
     "legendFormat": "Rating service"
    }
   ]
  },
  {
   "title": "Services requests count",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "http_server_requests_seconds_count{exception=\"None\",instance=\"info-service:8082\",job=\"info-service\",method=\"GET\",outcome=\"SUCCESS\",status=\"200\",uri=\"/movies/{movieId}\"}",
     "legendFormat": "Info service"
    },
    {
     "expr": "http_server_requests_seconds_count{exception=\"None\",instance=\"catalog-service:8081\",job=\"catalog-service\",method=\"GET\",outcome=\"SUCCESS\",status=\"200\",uri=\"/catalog/{movieId}\"}\t",
     "legendFormat": "Catalog service"
    },
    {
     "expr": "http_server_requests_seconds_count{exception=\"None\",instance=\"comments-service:8084\",job=\"comments-service\",method=\"GET\",outcome=\"SUCCESS\",status=\"200\",uri=\"/comments/{movieId}\"}\t",
     "legendFormat": "Comments service"
    },
    {
     "expr": "http_server_requests_seconds_count{exception=\"None\",instance=\"ratings-service:8083\",job=\"ratings-service\",method=\"GET\",outcome=\"SUCCESS\",status=\"200\",uri=\"/ratings/{movieId}\"}",
     "legendFormat": "Ratings service"
    }
   ]
  },
  {
   "title": "Comments created",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "http_server_requests_seconds_count{exception=\"None\",instance=\"comments-service:8084\",job=\"comments-service\",method=\"POST\",outcome=\"SUCCESS\",status=\"200\",uri=\"/comments\"}\t",
     "legendFormat": "Comments created"
    }
   ]
  }
 ]
}