# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

scrape_configs:
- job_name: prometheus
  static_configs:
  - targets: ['localhost:9090']

- job_name: catalog-service
  metrics_path: /actuator/prometheus
  static_configs:
  - targets: ['catalog-service:8081']

- job_name: info-service
  metrics_path: /actuator/prometheus
  static_configs:
  - targets: ['info-service:8082']

- job_name: ratings-service
  metrics_path: /actuator/prometheus
  static_configs:
  - targets: ['ratings-service:8083']

- job_name: comments-service
  metrics_path: /actuator/prometheus
  static_configs:
  - targets: ['comments-service:8084']
